---
platform: linux
image_resource:
  type: docker-image
  source: 
    repository: testcafe/testcafe
    tag: "latest"
inputs:
  - name: source-repo
run:
  path: sh
  user: root
  args:
    - -exc
    - |
      echo 'helloworld'
      testcafe --version
      cd ./source-repo
      npm install
      
      ls -lr

      mkdir -p testresults

      npm run test:automation:ci