
groups:  
  - name: overview
    jobs:
      - run-tests
   

#      _  ___  ___ ___
#   _ | |/ _ \| _ ) __|
#  | || | (_) | _ \__ \
#   \__/ \___/|___/___/
jobs:
- name: run-tests
  public: true
  plan:
  - get: source-repo
  - task: testcafe test job
    privileged: true
    file: source-repo/ci/tasks/testjob.yml


resources:
- name: source-repo
  type: git
  source:
    uri: https://github.com/ramakrishnakudikala/testcafeprototype.git
    branch: master
